[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 30
feature_words = true
feature_snippets = true
snippets_first = true
snippets_inline_by_word_tail = false
feature_unicode_input = false
feature_paths = false
feature_citations = false

[[language]]
name = "php"
language-servers = ["scls", "intelephense"]

[[language]]
name = "rust"
language-servers = ["scls", "rust-analyzer"]

[[language]]
name = "markdown"
language-servers = ["scls"]
